### ISSUE TITLE
Duplicate EO models under Resources

### ISSUE THREAD

**Issue by paulhoadley** [wocommunity/wolifecycle-maven-plugin#7]
This is an issue I brought up on Slack a couple of weeks ago. It turns out that it's a side-effect of the new `flattenComponents` option introduced in #3. In fact, you could argue it's not even a side-effect: it's fully documented behaviour for that option:

> Flatten only the WOComponents and EOModels from Resources or Components folders. All other files and directories keep their original nesting structure.

Here is the problem. Say you've got your models _and_ `.eogen` files in `src/main/resources/models`. If you set `flattenComponents` to true, the plug-in _does_ copy the models to `Resources` as advertised, _but_ (presumably because of the presence of the `.eogen` files) _doesn't_ then delete `src/main/resources/models`, or even delete just the models from that location. The result is that you've got a copy of any model `Foo.eomodeld` in _both_ `Resources` and `Resources/models` in the built package. Your application will complain about the duplication at start-up.

I think we have to call this result a bug: `flattenComponents` causes duplicate models in the built package under the conditions described above. I can see some potential solutions:

1. Maybe `flattenComponents` should just do one job (flatten components) and leave models alone.
2. You could definitely argue that the `.eogen` files aren't even needed in the built package, and if they can be pulled from the resources at the appropriate point, then `flattenComponents` _won't_ duplicate the models. (That is, it _will_ delete `Resources/models` and its contents in the example above if you put the `.eogen` files somewhere else.)

I tried using `woproject/resources.exclude.patternset` to achieve option 2 without success, but maybe someone else knows how to approach it?

Attached is a sample project created by @hprange to investigate the issue, with a single modification: it sets `flattenComponents` to demonstrate the issue. Run `mvn package` and observe:

```
elmo:Resources paulh$ ls -l
total 32
-rw-r--r--   1 paulh  staff  1451  3 Jul 08:46 Info.plist
drwxr-xr-x  12 paulh  staff   384  3 Jul 08:46 Java
-rw-r--r--   1 paulh  staff   142  3 Jul 08:46 Main.api
drwxr-xr-x   5 paulh  staff   160  3 Jul 08:46 Main.wo
drwxr-xr-x   4 paulh  staff   128  3 Jul 08:46 MyEOModel.eomodeld
-rw-r--r--   1 paulh  staff  4508  3 Jul 08:46 Properties
drwxr-xr-x   4 paulh  staff   128  3 Jul 08:46 models
elmo:Resources paulh$ cd models/
elmo:models paulh$ ls -l
total 8
-rw-r--r--  1 paulh  staff  195  3 Jul 08:46 MyEOModel.eogen
drwxr-xr-x  4 paulh  staff  128  3 Jul 08:46 MyEOModel.eomodeld
```

[wo-flatten-model-test.zip](https://github.com/wocommunity/wolifecycle-maven-plugin/files/4867033/wo-flatten-model-test.zip)

**Comment by hprange** [comment]
@paulhoadley I've deployed version 2.4-SNAPSHOT of the wolifecycle-maven-plugin, including the fix for this issue. Could you please try it and check if it's working as expected? I'll cut a new release as soon as we all agree on a solution to this problem.

**Comment by paulhoadley** [comment]
Thanks @hprange. I've commented over at #8.
