### ISSUE TITLE
Install fails for woapplication projects with maven-install-plugin version 3.0.0-M1

### ISSUE THREAD

**Issue by lbane** [wocommunity/wolifecycle-maven-plugin#9]
When installing a woapplication project (packaging `woapplication`,`mvn install`) with the maven-install-plugin 3.0.0-M1 the build fails with the message: 

> The packaging plugin for this project did not assign a main file to the project but it has attachments. Change packaging to 'pom'.

With a previous install-plugin version (e.g. 2.5.2) an info message is displayed instead: 

> No primary artifact to install, installing attached artifacts instead.

The 3.0.0 version of the install plugin demands from all non-POM-packaging projects a defined main artifact. AbstractPackageMojo.java does set a main project artifact file, but for woapplications the file name is probably invalid.

A simple solution (besides not using version 3.0.0 ;-) may be to define the application resource archive as the main artifact, and only attach the webserver resource archive.

**Comment by hprange** [comment]
Fixed by #12.
